//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSys.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class InSysEntities : DbContext
    {
        public InSysEntities()
            : base("name=InSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Answer> T_Answer { get; set; }
        public virtual DbSet<T_Candidate> T_Candidate { get; set; }
        public virtual DbSet<T_CategoryMaster> T_CategoryMaster { get; set; }
        public virtual DbSet<T_Exam> T_Exam { get; set; }
        public virtual DbSet<T_ExamCandidate> T_ExamCandidate { get; set; }
        public virtual DbSet<T_ExamQuestion> T_ExamQuestion { get; set; }
        public virtual DbSet<T_LevelCandidate> T_LevelCandidate { get; set; }
        public virtual DbSet<T_LevelQuestionMaster> T_LevelQuestionMaster { get; set; }
        public virtual DbSet<T_PercentQuestion> T_PercentQuestion { get; set; }
        public virtual DbSet<T_Question> T_Question { get; set; }
        public virtual DbSet<T_Result> T_Result { get; set; }
        public virtual DbSet<T_RoleMaster> T_RoleMaster { get; set; }
        public virtual DbSet<T_UserMaster> T_UserMaster { get; set; }
    
        public virtual ObjectResult<SP_GetQuestions_Result> SP_GetQuestions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetQuestions_Result>("SP_GetQuestions");
        }
    }
}
