//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSys.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Answer
    {
        public T_Answer()
        {
            this.T_Result = new HashSet<T_Result>();
        }
    
        public System.Guid AnswerId { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public string ContentAnswer { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> Point { get; set; }
        public Nullable<int> NumberAnswers { get; set; }
    
        public virtual T_Question T_Question { get; set; }
        public virtual ICollection<T_Result> T_Result { get; set; }
    }
}
