//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSys.Data
{
    using System;
    using System.Collections.Generic;
    
    using InSys.Repository.Pattern.Ef6;
    public partial class T_Candidate : Entity
    {
        public T_Candidate()
        {
            this.T_ExamCandidate = new HashSet<T_ExamCandidate>();
        }
    
        public System.Guid CandidateId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<double> YearOfExperience { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<int> LevelCandidateId { get; set; }
        public string Tags { get; set; }
    
        public virtual ICollection<T_ExamCandidate> T_ExamCandidate { get; set; }
        public virtual T_LevelCandidate T_LevelCandidate { get; set; }
    }

}
