//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSys.Data
{
    using System;
    using System.Collections.Generic;
    
    using InSys.Repository.Pattern.Ef6;
    public partial class T_ExamQuestion : Entity
    {
        public System.Guid ExamQuestionId { get; set; }
        public Nullable<System.Guid> ExamId { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public string Code { get; set; }
    
        public virtual T_Exam T_Exam { get; set; }
        public virtual T_Question T_Question { get; set; }
    }

}
