//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSys.Data
{
    using System;
    using System.Collections.Generic;
    
    using InSys.Repository.Pattern.Ef6;
    public partial class T_Exam : Entity
    {
        public T_Exam()
        {
            this.T_ExamCandidate = new HashSet<T_ExamCandidate>();
            this.T_ExamQuestion = new HashSet<T_ExamQuestion>();
        }
    
        public System.Guid ExamId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<double> TimeTest { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Code { get; set; }
        public string Tags { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberQuestions { get; set; }
    
        public virtual ICollection<T_ExamCandidate> T_ExamCandidate { get; set; }
        public virtual ICollection<T_ExamQuestion> T_ExamQuestion { get; set; }
    }

}
