//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSys.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LevelCandidate
    {
        public T_LevelCandidate()
        {
            this.T_Candidate = new HashSet<T_Candidate>();
            this.T_PercentQuestion = new HashSet<T_PercentQuestion>();
        }
    
        public int LevelCandidateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<T_Candidate> T_Candidate { get; set; }
        public virtual ICollection<T_PercentQuestion> T_PercentQuestion { get; set; }
    }
}
